### ISSUE TITLE
Optimize putMetrics - to avoid Cloudwatch throttling

### ISSUE THREAD

**Issue by prashantintellify** [camitz/aws-cloudwatch-statsd-backend#10]
This might be related to https://github.com/camitz/aws-cloudwatch-statsd-backend/issues/7

We see this in statsd.log - perhaps packing metrics might help?

```
Err : { StatusCode: 400,
  Headers:
   { 'x-amzn-requestid': '43732e6e-4618-11e6-9498-bf6b383bb542',
     'content-type': 'text/xml',
     'content-length': '261',
     date: 'Sat, 09 Jul 2016 21:01:10 GMT' },
  Body:
   { ErrorResponse:
      { '@': { xmlns: 'http://monitoring.amazonaws.com/doc/2010-08-01/' },
        Error:
         { Type: 'Sender',
           Code: 'Throttling',
           Message: 'Rate exceeded' },
        RequestId: '43732e6e-4618-11e6-9498-bf6b383bb542' } } }
```

Bumping up default statsd flushInterval to 20, 30 s does not seem to help

**Comment by prashantintellify** [comment]
Hello - I created a PR for this and other issues we saw when using this in

https://github.com/camitz/aws-cloudwatch-statsd-backend/pull/12

**Comment by orlando** [comment]
@prashantintellify should we close this, since #12 was merged?

**Comment by camitz** [comment]
ok.
