### ISSUE TITLE
Support IAM Roles for authentication

### ISSUE THREAD

**Issue by colinbankier** [camitz/aws-cloudwatch-statsd-backend#11]
Currently it is required to specify `accessKeyId` and `secretAccessKey`. It would be great if this backend could utilize IAM roles for authentication when running on EC2.

For more info see: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

**Comment by joachimroeleveld** [comment]
This is already supported. See the section 'Using AWS Roles to obtain credentials'.

**Comment by colinbankier** [comment]
Great, thanks. I must have missed that section when I opened the issue.
